<a href="https://colab.research.google.com/github/dhrish-s/PythonLearning/blob/main/Lasso_and_Ridge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("Salary_Data.csv")
df.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [ ]:
x=df.iloc[:,[0]]
y=df.iloc[:,[1]]

In [ ]:
x

YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [ ]:
y

Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [ ]:
x_train

YearsExperience
10              3.9
26              9.5
8               3.2
13              4.1
24              8.7
18              5.9
25              9.0
17              5.3
16              5.1
0               1.1
29             10.5
20              6.8
19              6.0
11              4.0
5               2.9
14              4.5
23              8.2
3               2.0
2               1.5
22              7.9
12              4.0
21              7.1
6               3.0
4               2.2

In [ ]:
x_test

YearsExperience
7               3.2
27              9.6
28             10.3
1               1.3
9               3.7
15              4.9

In [ ]:
y_train

Salary
10   63218.0
26  116969.0
8    64445.0
13   57081.0
24  109431.0
18   81363.0
25  105582.0
17   83088.0
16   66029.0
0    39343.0
29  121872.0
20   91738.0
19   93940.0
11   55794.0
5    56642.0
14   61111.0
23  113812.0
3    43525.0
2    37731.0
22  101302.0
12   56957.0
21   98273.0
6    60150.0
4    39891.0

In [ ]:
y_test

Salary
7    54445.0
27  112635.0
28  122391.0
1    46205.0
9    57189.0
15   67938.0

In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [ ]:
pred=lr.predict(x_test)
pred

array([[ 55749.3539212 ],
       [117852.90306846],
       [124645.47875644],
       [ 37312.3627681 ],
       [ 60601.19369833],
       [ 72245.60916344]])

In [ ]:
print(lr.coef_)
print(lr.intercept_)

[[9703.67955426]]
[24697.57934757]


In [ ]:
from sklearn.linear_model import Lasso,Ridge
ridge=Ridge(alpha=1)
ridge.fit(x_train,y_train)
r_pred=ridge.predict(x_test)
r_pred

array([[ 55868.78619427],
       [117602.48056041],
       [124354.6033817 ],
       [ 37541.59567932],
       [ 60691.73106662],
       [ 72266.79876027]])

In [ ]:
lasso=Lasso(alpha=1)
lasso.fit(x_train,y_train)
l_pred=lasso.predict(x_test)
l_pred

array([ 55749.6510814 , 117852.27999061, 124644.75502756,  37312.93312398,
        60601.41896493,  72245.66188541])

In [ ]:
ridge.coef_

array([[9645.88974471]])

In [ ]:
ridge.intercept_

array([25001.9390112])

In [ ]:
lasso.intercept_

array([24698.33662679])

In [ ]:
lasso.coef_

array([9703.53576706])